#cloud-config

package_upgrade: true

packages:
  - nginx
  - git

write_files:
  - owner: www-data:www-data
    path: /etc/nginx/sites-available/default
    content: |
      server {
        listen 80 default_server;
        server_name _;
        location / {
          try_files $uri @app;
        }
        location @app {
          proxy_pass http://localhost:5173;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection 'upgrade';
          proxy_set_header X-Forwarded-For $remote_addr;
          proxy_set_header Host $host;
          proxy_cache_bypass $http_upgrade;
        }
      }

runcmd:
  - curl -sL https://deb.nodesource.com/setup_20.x | sudo -E bash -
  - sudo apt install -y nodejs npm
  - cd /home/ubuntu
  - git clone "https://github.com/vesic/ai-code-assistant" ai-code-assistant
  - cd ai-code-assistant && npm install && npm run dev
  - systemctl restart nginx
